[package]
name = "sharex-vault-backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10.13"
ic-cdk = "0.12.2"
ic-cdk-timers = "0.6.0"
serde_bytes = "0.11.17"
serde = { version = "1.0", features = ["derive"] }
ic-stable-structures = "0.5.6"
